# Generated by Django 2.0.1 on 2018-01-13 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='student_num',
        ),
    ]
